### ISSUE TITLE
Admin usernames can not include dots

### ISSUE THREAD

**Issue by alfem** [gecos-team/gecoscc-ui#11]
In corporative world usernames with dots (separating first name and last name, for example) are very common.

Control Center admin users can not include a dot, possibly due to a Chef constraint.

However, workstation users in the organizational tree can include dots, as they are translated back and forth to "###" when needed. 

Suggestion: A sanitize username function could be useful for both kind of users.

**Comment by System25** [comment]
Hi Alfonso,
 Control Center admin users are limited to lower case letters and numbers:
  https://github.com/gecos-team/gecoscc-ui/blob/master/gecoscc/models.py

class LowerAlphaNumeric(object):
    err_msg = _('Only lowercase letters or numbers')
    regex = re.compile(r'^([a-z]|[0-9])*$')
    def __call__(self, node, value):
        if not self.regex.match(value):
            node.raise_invalid(self.err_msg)


 Chef usernames are sanitized by replacing the dots by underscores:
   https://github.com/chef/chef-server-webui/blob/master/app/models/user.rb
 
  def name=(n)
    @name = n.gsub(/\./, '_')
  end

  Also Chef saves the user via the REST API so the username must create a proper URI, so it must be limited to [ ALPHA / DIGIT / "-" / "_" / "~" ]

Maybe the sanitize function must force the username to match the following regular expression: [A-Za-z0-9\-_~]

Do you think that "admin usernames " and "workstation usernames" must be sanitized by using this regular expression?

**Comment by alfem** [comment]
Yes, it looks a pretty straight forward solution, although I think that regexp must be implemented in our Control Center before saving/retrieving admin useres to/from Chef.

**Comment by System25** [comment]
Testing with different usernames in the Chef Server administration area I noticed that the usernames must be in lower case and the "~" characters also is forbidden.
To the final regular expression to match is [a-z0-9\\-_]
