### ISSUE TITLE
Deleted objects can be assigned

### ISSUE THREAD

**Issue by alfem** [gecos-team/gecoscc-ui#18]
Following a specific (and odd) procedure, Printers, Software Profiles and Storage objects can be assigned to OUs even when they have been recently deleted.

Test Case:

- Create a new printer
- Assign it to a OU using 'available printers' policy. Save it, but do not apply this change
- Delete the printer (using a different window in your browser)
- Apply the change now
- Check the policy: a weird error shows up.

**Comment by System25** [comment]
Created a patch for this. 
Best regards
