### ISSUE TITLE
Policies do not merge as expected

### ISSUE THREAD

**Issue by alfem** [gecos-team/gecoscc-ui#20]
A computer or user receives policy attributes from OUs, groups and (software) profiles. 

Attributes priority is not resolved properly when many origins merge in a computer/user or when these atrributes are (by instinct) additive. 

Besides, current behaviour is poorly documented.

Some discussion could be necessary before implementation.

**Comment by iPablo** [comment]
Before these PRs [1][2] when you add a policy to a node (ws, user, OU or group) GCC-UI, this policy was applied in priority order:
 1 - Users or workstations have the highest level of priority
 2 - Groups: These have the second level of priority. Between two groups, the priority is for proximity, if they have the same proximity, the priority is in order of arrival.
 3 - OUs: These have the lowest level of priority. Between two OUs, the priority is by proximity and in this case the OUs can't have the same proximity.

With the next PRs[1][2], there are two kind of policies, mergeable and no-mergeable:
 1 - The priority of the no-mergeable policies work like before these PRs.
 2 - The mergeable policies do not have priority, now the policies values will be a set with the values of every policy applied to this node.    

How to update:
 1 - Update the cookbook
 2 - Run the recalc_nodes_policies command.

You can run this command in a similar way that import_policies command:
    All computers: pmanage CONFIG.ini recalc_nodes_policies -a SUPER_USER
    Computers from a domain: pmanage CONFIG.ini recalc_nodes_policies -a SUPER_USER -d MONGO_DOMAIN_ID
    List of computers: pmanage CONFIG.ini recalc_nodes_policies -a SUPER_USER -c MONOGO_COMPUTER_ID -c ANOTHER_MONGO_COMPUTER_ID ...

1 - https://github.com/gecos-team/gecoscc-ui/pull/39
2- https://github.com/gecos-team/gecos-workstation-management-cookbook/pull/134
