### ISSUE TITLE
Visibility errors

### ISSUE THREAD

**Issue by iPablo** [gecos-team/gecoscc-ui#27]
This error may occur in several cases:

When we try to associate a user with a group which is out of user's scope, the association is done successfully instead of getting an error (e.g. when associating a group inside an Organisational Unit with a user which is located outside from this OU).

When we try to add a policy to a group or a workstation using related objects (printers, storages or repositories) which are out of group's/workstation's scope. You can successfully add the policy instead of getting an error (e.g. groups and printers in different OUs in the same Domain's level).

**Comment by alfem** [comment]
Do you mean backend allows this wrong association?

I am testing it from the webui front-end  and I can not add a group out of scope.

**Comment by iPablo** [comment]
Yes, and this is a security problem.

If you send a request to update a node (put method), the application allowed (without this commit) you add a group out of scope, there were the same problem with printers, storages and repositories.

**Comment by alfem** [comment]
Of course it is!

Serious developers never trust in front-end validations alone.
